// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wromzrsdywgiamejssrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indyb216cnNkeXdnaWFtZWpzc3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTcyODgsImV4cCI6MjA2MDY3MzI4OH0.qqMlmmzXAanPyKrMEhyHxYYTvzLqQEnFNmOCT27jBuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);